# Generated by Django 4.0.3 on 2022-04-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_first_name_alter_user_id_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermidiate'), ('E', 'Expert')], max_length=1),
        ),
    ]
